CREATE TABLE `yibai_amazon_account` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `account_type` tinyint(1) NOT NULL DEFAULT '0' COMMENT '店铺来源  0 系统自建  1销售系统  2分销系统',
  `partner_id` varchar(64) NOT NULL DEFAULT '' COMMENT '平台商户ID',
  `partner_name` varchar(50) NOT NULL DEFAULT '' COMMENT '账号',
  `account_id` int(11) NOT NULL COMMENT '平台店铺ID',
  `group_id` int(11) NOT NULL DEFAULT '0' COMMENT '账号所属组',
  `account_name` varchar(50) NOT NULL COMMENT '账号站点',
  `account_real_name` varchar(50) NOT NULL DEFAULT '' COMMENT '账号简称',
  `account_num_name` varchar(64) NOT NULL DEFAULT '' COMMENT '账号店铺名',
  `distributor_id` int(11) NOT NULL DEFAULT '0' COMMENT '商户id',
  `account_email` varchar(255) NOT NULL DEFAULT '' COMMENT '平台店铺邮箱',
  `account_sales_plan` tinyint(1) NOT NULL DEFAULT '1' COMMENT '账号销售计划 1专业 2个人',
  `is_leave_account` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否休假账号 1否 2是',
  `site_id` varchar(20) NOT NULL COMMENT '站点ID',
  `auth_url` varchar(255) NOT NULL DEFAULT '' COMMENT '授权链接',
  `auth_status` tinyint(2) NOT NULL DEFAULT '0' COMMENT '授权状态：0未授权 1已授权 2 授权异常',
  `auth_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '授权时间',
  `auth_end_time` timestamp NULL DEFAULT '0000-00-00 00:00:00' COMMENT '授权到期时间',
  `app_id` varchar(255) NOT NULL DEFAULT '' COMMENT '开发者ID',
  `selling_partner_id` varchar(50) NOT NULL DEFAULT '' COMMENT '店铺平台selling_partner_id',
  `mws_auth_token` varchar(255) NOT NULL DEFAULT '' COMMENT 'mws_auth_token值',
  `access_token` varchar(2048) NOT NULL DEFAULT '' COMMENT '授权TOKEN',
  `refresh_token` varchar(2048) NOT NULL COMMENT '刷新token',
  `expires_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '过期时间',
  `expires_in` int(11) NOT NULL COMMENT '过期时长',
  `auth_message` varchar(255) NOT NULL DEFAULT '' COMMENT '授权时平台返回信息(异常时录入)',
  `account_status` tinyint(3) NOT NULL DEFAULT '10' COMMENT '10  启用 20 停用 30 异常 40 删除',
  `account_reason` varchar(255) NOT NULL DEFAULT '' COMMENT '异常原因',
  `authcode_secret_key` varchar(80) NOT NULL DEFAULT '' COMMENT '验证码秘钥',
  `boss_comp` varchar(128) NOT NULL DEFAULT '' COMMENT 'boss公司',
  `reg_comp` varchar(128) NOT NULL DEFAULT '' COMMENT '注册公司',
  `first_name` varchar(64) NOT NULL DEFAULT '' COMMENT 'first_name',
  `last_name` varchar(64) DEFAULT '' COMMENT 'last_name',
  `created_time` timestamp NULL DEFAULT '0000-00-00 00:00:00' COMMENT '添加时间',
  `create_name` varchar(32) NOT NULL DEFAULT '' COMMENT '创建人',
  `is_push_status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '已授权推送平台状态  0 未推送  1 已推送',
  `push_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '推送时间',
  `update_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '修改时间',
  `update_name` varchar(32) NOT NULL DEFAULT '' COMMENT '修改人',
  `refresh_status` tinyint(1) NOT NULL DEFAULT '1' COMMENT '刷新状态：1正常，2异常',
  `refresh_num` int(2) NOT NULL DEFAULT '0' COMMENT '刷新异常次数',
  `refresh_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '最近Token刷新时间',
  `refresh_msg` varchar(500) NOT NULL DEFAULT '' COMMENT '刷新异常信息',
  `refresh_date` date DEFAULT '0000-00-00' COMMENT '异常刷新日期',
  `leave_time` date NOT NULL DEFAULT '0000-00-00' COMMENT '休假时间',
  `is_adjustment` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否调价1否，2是',
  `is_stocking` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否备货 1否，2是',
  `is_pull_order` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否开启拉单 1是 2否',
  `restricted_token` varchar(2500) NOT NULL DEFAULT '' COMMENT '受限token',
  `restricted_expires_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '受限token过期时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `partner_id` (`partner_id`) USING BTREE,
  KEY `account_name` (`account_name`) USING BTREE,
  KEY `account_s_name` (`account_real_name`) USING BTREE,
  KEY `account_id` (`account_id`) USING BTREE,
  KEY `selling_partner_id` (`selling_partner_id`) USING BTREE,
  KEY `account_type` (`account_type`) USING BTREE,
  KEY `idx_refresh_status` (`refresh_status`) USING BTREE,
  KEY `idx_refresh_num` (`refresh_num`) USING BTREE,
  KEY `idx_restricted_time` (`restricted_expires_time`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='亚马逊账户列表';

